-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 13:21:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attendance` (
  `idAtendance` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT NOT NULL,
  `atendanceDay` DATE NOT NULL,
  `attendanceStart` TIME NOT NULL,
  `attendanceEnd` TIME NULL,
  PRIMARY KEY (`idAtendance`),
  INDEX `fk_dochadzka_zamestnanec1_idx` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_dochadzka_zamestnanec1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typ kontaktu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typ kontaktu` (
  `idtyp kontaktu` INT NOT NULL,
  `typKontaktu` INT NULL,
  `kontakt` VARCHAR(45) NULL,
  PRIMARY KEY (`idtyp kontaktu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `idPosition` INT NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPosition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personHasPossition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personHasPossition` (
  `idPositionStamp` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT NOT NULL,
  `idPosition` INT NOT NULL,
  `positionFrom` DATE NULL,
  `positionTo` DATE NULL,
  PRIMARY KEY (`idPositionStamp`),
  INDEX `fk_zamPracPoz_zamestnanec1_idx` (`idPerson` ASC) VISIBLE,
  INDEX `fk_zamPracPoz_pracovnaPozicia1_idx` (`idPosition` ASC) VISIBLE,
  CONSTRAINT `fk_zamPracPoz_zamestnanec1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamPracPoz_pracovnaPozicia1`
    FOREIGN KEY (`idPosition`)
    REFERENCES `mydb`.`position` (`idPosition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission` (
  `idPermission` INT NOT NULL AUTO_INCREMENT,
  `permName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personHasPermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personHasPermission` (
  `idPersonPerm` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT NOT NULL,
  `idPermission` INT NOT NULL,
  `permFrom` DATE NULL,
  `permTo` DATE NULL,
  PRIMARY KEY (`idPersonPerm`),
  INDEX `fk_table1_zamestnanec1_idx` (`idPerson` ASC) VISIBLE,
  INDEX `fk_table1_table21_idx` (`idPermission` ASC) VISIBLE,
  CONSTRAINT `fk_table1_zamestnanec1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_table21`
    FOREIGN KEY (`idPermission`)
    REFERENCES `mydb`.`permission` (`idPermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `idDocument` INT NOT NULL AUTO_INCREMENT,
  `nameDoc` VARCHAR(45) NOT NULL,
  `textDoc` TEXT NOT NULL,
  `validityFrom` DATE NOT NULL,
  `validityTo` DATE NULL,
  PRIMARY KEY (`idDocument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personHasDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personHasDocument` (
  `idDocument` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `dateOfSign` DATETIME NULL,
  `cancelationOfSign` DATETIME NULL,
  PRIMARY KEY (`idDocument`, `idPerson`),
  INDEX `fk_dokumenty_has_osoba_osoba1_idx` (`idPerson` ASC) VISIBLE,
  INDEX `fk_dokumenty_has_osoba_dokumenty1_idx` (`idDocument` ASC) VISIBLE,
  CONSTRAINT `fk_dokumenty_has_osoba_dokumenty1`
    FOREIGN KEY (`idDocument`)
    REFERENCES `mydb`.`document` (`idDocument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokumenty_has_osoba_osoba1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `idLog` INT NOT NULL AUTO_INCREMENT,
  `logWhatsGoingOn` VARCHAR(45) NOT NULL,
  `logDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idLog`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
